### PR TITLE
Add opensea api key

### LINKED ISSUE #24: Need to get opensea api key
"We will no longer allow un-keyed access to any of our endpoints." https://twitter.com/apiopensea/status/1661369002718027778

Fortunately they allow us to get an api key automatically now: https://docs.opensea.io/reference/api-keys

### PR DESCRIPTION
**Pull request by fafrd**
resolves #24

### CODE REVIEW

**Comment by fafrd** [comment]
@crypt0biwan Do you know how to fix the circleci check? I don't see where I would add the new OPENSEA_API_KEY env var for the test to succeed, i probably don't have permissions for that? I can DM you an opensea api key (though you should be able to request one yourself now- https://docs.opensea.io/reference/api-keys)

**Comment by crypt0biwan** [comment]
Think we have to make a mock request just like the Twitter media upload? Since we don’t want the key in Github..

Here’s the test: https://github.com/crypt0biwan/curio-sales-bot/blob/42b594807fe28ba424ad14f2ef359e1ebdefbe73/test/testWatcher.js#L142

**Comment by fafrd** [comment]
Thanks- that's a good call about the mocked call

**Comment by fafrd** [comment]
Looks like this is working, and the discord bot is actively broken due to this, so i'm going to go ahead and merge

**Pull request merged**
